### ISSUE TITLE
Are you open for Rust opportunities

### ISSUE THREAD

**Issue by heyong4725** [weihanglo/weihanglo#1]
Hi Wenhang,

I noticed that you are active in Rust community, and also in Cargo project. I have some good open source projects opportunities, and wondering if you are open for the open source project development.

Ed Page in Cargo project works in our company, Futurewei Technologies, Inc.

If you are interested, please let me know.

Thanks,
Yong

**Comment by weihanglo** [comment]
Thanks for reaching me, @heyong4725. We can have further conversation on either [Telegram](https://t.me/weihanglo) or [LinkedIn](https://www.linkedin.com/in/weihanglo). Cheers!

**Comment by weihanglo** [comment]
BTW, I am excited in seeing Futurewei investing in Rust more and more. Really look forward to future opportunities in any form of cooperation!

**Comment by weihanglo** [comment]
This is the post that changed my thought on Futurewei: https://www.reddit.com/r/rust/comments/ubngsb/comment/i65yh1i/

**Comment by heyong4725** [comment]
Wei Hang,

I am glad you are interested. Indeed Futurewei is investing in Rust and WASM because these are foundational technologies. 
What’s your email address? I will send you a Zoom invite to further discuss. 

Cheers,
Yong

**Comment by weihanglo** [comment]
Hi. I prefer to use instant messaging listed in my profile first and have a video call afterward. Thanks!

**Comment by heyong4725** [comment]
OK. I only use LinkedIn. I will send you a LinkedIn request.
