### ISSUE TITLE
Asking for depreciation notice on sfz to link to my repo

### ISSUE THREAD

**Issue by mu-arch** [weihanglo/weihanglo#2]
hello I was a contributor to https://github.com/weihanglo/sfz

I have since decided to make my own HTTP file server project but with many more features:

https://github.com/mu-arch/skyfolder

Currently it is not ready but I plan to have it working at the point sfz was in the next few days. 

To the point: I humbly ask if you would link your old repository to my project! :)

Let me know if you have any questions

**Comment by weihanglo** [comment]
Hi. It is fantastic to see so many awesome Rust projects in the wild. I deeply appreciate everybody's effort on their beloved project. Sorry to inform you that sfz has been archived, and at this time, I have no plan to unarchived it and add a notice. Additionally, I typically endorse tools that I have personally used, so if I do start using skyfolder in the future, I may have a second thought on that. Thank you for your understanding.
